name: Deploy back-to-kps to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if you use a different branch for deployment

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          GOOGLE_SHEET_API_KEY: ${{ secrets.GOOGLE_SHEET_API_KEY }}
        run: |
          echo "window.GOOGLE_MAPS_API_KEY='${GOOGLE_MAPS_API_KEY}';" >> back-to-kps/env.js
          echo "window.GOOGLE_SHEET_API_KEY='${GOOGLE_SHEET_API_KEY}';" >> back-to-kps/env.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./back-to-kps
